#ifndef SWAY_PLTF_WINDOWEVENTTYPES_HPP
#define SWAY_PLTF_WINDOWEVENTTYPES_HPP

#include <sway/core.hpp>

NAMESPACE_BEGIN(sway)
NAMESPACE_BEGIN(pltf)

enum class WindowEventType : u32_t {
  SIZE_CHANGE,
  RESOLUTION_CHANGE,
  FULLSCREEN_CHANGE,
  SCREEN_CHANGE,
  FOCUS_CHANGE,
  CLOSE,
  SHOW,
  HIDE,
  MINIMIZE,
  MAXIMIZE,
  RESTORE
};

NAMESPACE_END(pltf)
NAMESPACE_END(sway)

#endif  // SWAY_PLTF_WINDOWEVENTTYPES_HPP
