#ifndef SWAY_PLTF_TYPEDEFS_HPP
#define SWAY_PLTF_TYPEDEFS_HPP

#include <sway/core.hpp>

NS_BEGIN_SWAY()
NS_BEGIN(pltf)

DECLARE_CLASS_POINTER_TYPES(Context)
DECLARE_CLASS_POINTER_TYPES(Loopeable)

DECLARE_CLASS_POINTER_TYPES(DTPScreenConnection)
DECLARE_CLASS_POINTER_TYPES(DTPContext)
DECLARE_CLASS_POINTER_TYPES(DTPCanvas)

NS_END()  // namespace pltf
NS_END()  // namespace sway

#endif  // SWAY_PLTF_TYPEDEFS_HPP
