#ifndef SWAY_PLTF_WINDOWEVENTTYPES_HPP
#define SWAY_PLTF_WINDOWEVENTTYPES_HPP

#include <sway/core.hpp>

NS_BEGIN_SWAY()
NS_BEGIN(pltf)

enum class WindowEventType : u32_t {
  SIZE_CHANGE,
  RESOLUTION_CHANGE,
  FULLSCREEN_CHANGE,
  SCREEN_CHANGE,
  FOCUS_CHANGE,
  CLOSE,
  SHOW,
  HIDE,
  MINIMIZE,
  MAXIMIZE,
  RESTORE
};

NS_END()  // namespace pltf
NS_END()  // namespace sway

#endif  // SWAY_PLTF_WINDOWEVENTTYPES_HPP
